import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#006e2f',
        'on-primary': '#ffffff',
        'primary-container': '#22c55e',
        'on-primary-container': '#004b1e',
        'primary-fixed': '#6bff8f',
        'primary-fixed-dim': '#4ae176',
        'inverse-primary': '#4ae176',
        'on-primary-fixed': '#002109',
        'on-primary-fixed-variant': '#005321',
        secondary: '#565e74',
        'on-secondary': '#ffffff',
        'secondary-container': '#dae2fd',
        'on-secondary-container': '#5c647a',
        'secondary-fixed': '#dae2fd',
        'secondary-fixed-dim': '#bec6e0',
        'on-secondary-fixed': '#131b2e',
        'on-secondary-fixed-variant': '#3f465c',
        tertiary: '#005ac2',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#82abff',
        'on-tertiary-container': '#003d88',
        'tertiary-fixed': '#d8e2ff',
        'tertiary-fixed-dim': '#adc6ff',
        'on-tertiary-fixed': '#001a42',
        'on-tertiary-fixed-variant': '#004395',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#006e2f',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#3d4a3d',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        outline: '#6d7b6c',
        'outline-variant': '#bccbb9',
        // Status colors
        reserved: '#F59E0B',
        'reserved-bg': '#FEF3C7',
        sold: '#94A3B8',
        'sold-bg': '#F1F5F9',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        display: ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        montserrat: ['var(--font-montserrat)', 'Montserrat', 'sans-serif'],
        inter: ['var(--font-inter)', 'Inter', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'number-grid': ['14px', { lineHeight: '14px', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '24px',
        'margin-mobile': '16px',
        'margin-desktop': '64px',
        'grid-gap': '8px',
      },
      boxShadow: {
        card: '0 4px 6px -1px rgba(15, 23, 42, 0.05)',
        'card-hover': '0 10px 15px -3px rgba(15, 23, 42, 0.08)',
        modal: '0 20px 25px -5px rgba(15, 23, 42, 0.1)',
        'number-inset': 'inset 0 2px 4px 0 rgba(15, 23, 42, 0.1)',
        focus: '0 0 0 3px rgba(0, 110, 47, 0.25)',
      },
      maxWidth: {
        'layout': '1200px',
      },
    },
  },
  plugins: [],
}

export default config
